apiVersion: v1
kind: Service              
metadata:
  name: called-loadbalancer
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  called_mapping
      prefix: /called-loadbalancer/
      service: called-loadbalancer:80
      host_rewrite: http://called-loadbalancer
spec:
  type: LoadBalancer       
  ports:
  - port: 80               
    targetPort: 8081        
  selector:            
    app: called    
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: called
  labels:
    app: called
spec:
  replicas: 2                                             
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  selector:
    matchLabels:
      app: called
      tier: caller-called
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: called
        tier: caller-called
    spec:
      containers:
      - image: alessandroargentieri/called-called
        name: called
        env:
        - name: CALLEDPORT
          value: "8081"
        ports:
        - containerPort: 8081
          name: called