apiVersion: v1
kind: Service              
metadata:
  name: caller-loadbalancer
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  caller_mapping
      prefix: /caller-loadbalancer/
      service: caller-loadbalancer:80
      host_rewrite: http://caller-loadbalancer
spec:
  type: LoadBalancer       
  ports:
  - port: 80               
    targetPort: 8080        
  selector:            
    app: caller    
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: caller
  labels:
    app: caller
spec:
  replicas: 2                                             
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  selector:
    matchLabels:
      app: caller
      tier: caller-called
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: caller
        tier: caller-called
    spec:
      containers:
      - image: alessandroargentieri/caller-caller
        name: caller
        env:
        - name: CALLERPORT
          value: "8080"
        - name: CALLEDADDRESS
          value: "http://ambassador/called-loadbalancer"
        ports:
        - containerPort: 8080
          name: caller